version: '3.8'

services:
  backend:
    image: citybrain_bigdata:latest
    ports:
      - "8002:8002"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - city_brain_net

  # Airflow
  airflow:
    image: apache/airflow:3.0.0-python3.9
    container_name: airflow
    depends_on:
      - postgres
    environment:
      - TZ=Asia/Shanghai
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow%401313123@postgres/airflow
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=true
      - DATAX_PATH=C:/Users/Administrator/code/CityBrain/data/datax
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock # 允许 Airflow 访问 Windows 的 Docker 守护进程
      - ./data/airflow/dags:/opt/airflow/dags
      - ./logs/airflow:/opt/airflow/logs
      - ./data/airflow/simple_auth_manager_passwords.json.generated:/opt/airflow/simple_auth_manager_passwords.json.generated
    ports:
      - "8082:8080"
    command: bash -c "airflow db migrate && airflow standalone"
    networks:
      - city_brain_net

  # 数据库
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345HTW
      - POSTGRES_DB=city_brain
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5555:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin && PGPASSWORD=12345HTW psql -U admin -d city_brain -c 'SELECT 1'" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - city_brain_net

networks:
  city_brain_net:
    driver: bridge
